const users = [
  {
    email: "tyrone.stamaria35@gmail.com",
    firstName: "Tyrone",
    lastName: "Sta. Maria",
    password: "$2b$08$UOcRNA0jxfsR0qYLwyDGZudmp8HwAHCOioWJt6X4fgDvL7wVXcx9G",
    role: "user",
    upvotes: [],
    downvotes: [],
    suspended: false,
    favorites: [],
  },
  {
    email: "tyrone_stamaria@dlsu.edu.ph",
    firstName: "moderator",
    lastName: "moderator",
    password: "$2a$08$lDzGK/zfvAhK4ahnVQW9c.5YnuGmdy3vNjlrKgglB4oF8BZfmKazm",
    role: "moderator",
  },
  {
    email: "glenaestebal@gmail.com",
    firstName: "Glena",
    lastName: "Estebal",
    password: "$2b$08$UOcRNA0jxfsR0qYLwyDGZudmp8HwAHCOioWJt6X4fgDvL7wVXcx9G",
    role: "user",
    upvotes: [],
    downvotes: [],
    suspended: false,
    favorites: [],
  },
  {
    email: "gavindizon@gmail.com",
    firstName: "Gavin",
    lastName: "Dizon",
    password: "$2b$08$UOcRNA0jxfsR0qYLwyDGZudmp8HwAHCOioWJt6X4fgDvL7wVXcx9G",
    role: "user",
    upvotes: [],
    downvotes: [],
    suspended: false,
    favorites: [],
  },
  {
    email: "vinceesquivel@gmail.com",
    firstName: "Vince",
    lastName: "Esquivel",
    password: "$2b$08$UOcRNA0jxfsR0qYLwyDGZudmp8HwAHCOioWJt6X4fgDvL7wVXcx9G",
    role: "user",
    upvotes: [],
    downvotes: [],
    suspended: false,
    favorites: [],
  },
  {
    email: "wilfredgo@gmail.com",
    firstName: "Wilfred",
    lastName: "Go",
    password: "$2b$08$UOcRNA0jxfsR0qYLwyDGZudmp8HwAHCOioWJt6X4fgDvL7wVXcx9G",
    role: "user",
    upvotes: [],
    downvotes: [],
    suspended: false,
    favorites: [],
  },
  {
    email: "rileyuy@gmail.com",
    firstName: "Riley",
    lastName: "Uy",
    password: "$2b$08$UOcRNA0jxfsR0qYLwyDGZudmp8HwAHCOioWJt6X4fgDvL7wVXcx9G",
    role: "user",
    upvotes: [],
    downvotes: [],
    suspended: false,
    favorites: [],
  },
  {
    email: "abigailventucillo@gmail.com",
    firstName: "Abigail",
    lastName: "Ventucillo",
    password: "$2b$08$UOcRNA0jxfsR0qYLwyDGZudmp8HwAHCOioWJt6X4fgDvL7wVXcx9G",
    role: "user",
    upvotes: [],
    downvotes: [],
    suspended: false,
    favorites: [],
  },
  {
    email: "alessandrozapanta@gmail.com",
    firstName: "Alessandro",
    lastName: "Zapanta",
    password: "$2b$08$UOcRNA0jxfsR0qYLwyDGZudmp8HwAHCOioWJt6X4fgDvL7wVXcx9G",
    role: "user",
    upvotes: [],
    downvotes: [],
    suspended: false,
    favorites: [],
  },
  {
    email: "shannatan@gmail.com",
    firstName: "Shanna",
    lastName: "Tan",
    password: "$2b$08$UOcRNA0jxfsR0qYLwyDGZudmp8HwAHCOioWJt6X4fgDvL7wVXcx9G",
    role: "user",
    upvotes: [],
    downvotes: [],
    suspended: false,
    favorites: [],
  },
  {
    email: "lopentipan@gmail.com",
    firstName: "Loben",
    lastName: "Tipan",
    password: "$2b$08$UOcRNA0jxfsR0qYLwyDGZudmp8HwAHCOioWJt6X4fgDvL7wVXcx9G",
    role: "user",
    upvotes: [],
    downvotes: [],
    suspended: false,
    favorites: [],
  },
  {
    email: "ralphviceral@gmail.com",
    firstName: "Ralph",
    lastName: "Viceral",
    password: "$2b$08$UOcRNA0jxfsR0qYLwyDGZudmp8HwAHCOioWJt6X4fgDvL7wVXcx9G",
    role: "user",
    upvotes: [],
    downvotes: [],
    suspended: false,
    favorites: [],
  },
  {
    email: "angelyabut@gmail.com",
    firstName: "Angel",
    lastName: "Yabut",
    password: "$2b$08$UOcRNA0jxfsR0qYLwyDGZudmp8HwAHCOioWJt6X4fgDvL7wVXcx9G",
    role: "user",
    upvotes: [],
    downvotes: [],
    suspended: false,
    favorites: [],
  },
];

module.exports = users;
